### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by qbert911** [akulakov/geduld#1]
PS C:\Users\ben\code\geduld> python3 .\geduld.py

Traceback (most recent call last):
  File ".\geduld.py", line 2313, in <module>
    main(load_game)
  File ".\geduld.py", line 1725, in main
    getattr(b, f'board_{y}_{x}')()
  File ".\geduld.py", line 430, in board_0_0
    containers[3].add1(ID.key1)
IndexError: list index out of range

**Comment by akulakov** [comment]
The game is currently in an alpha / buggy / barely playable state, please
check back in a few weeks! Apologies..
